// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TodoId } from "../domain/TodoId";

/**
 * Commands that can be sent to the Todo aggregate.
 *
 * Each command represents a user intention. The aggregate validates
 * the command against its current state and either:
 *
 * - Emits events (success)
 * - Returns an error (validation failure)
 *
 * Commands are deserialized from HTTP requests (via datastar signals)
 * and routed to the appropriate aggregate.
 */
export type TodoCommand = { "type": "Create", 
/**
 * Client-generated unique identifier.
 */
id: TodoId, 
/**
 * Raw text input (will be validated and trimmed).
 */
text: string, } | { "type": "UpdateText", 
/**
 * Which todo to update.
 */
id: TodoId, 
/**
 * New text content (raw, will be validated).
 */
text: string, } | { "type": "Complete", 
/**
 * Which todo to complete.
 */
id: TodoId, } | { "type": "Uncomplete", 
/**
 * Which todo to uncomplete.
 */
id: TodoId, } | { "type": "Delete", 
/**
 * Which todo to delete.
 */
id: TodoId, };
