keys:
  - &dev age1454mdqee7jtunm2an0amk50d6x8t0ahypvqmrwyp7weu69l7rv6q5ehcu5
  - &ci age1ecp3fw2w0wyt9hde40zs4uyfdj8nhe3vrmh24hwzh8sgzhm5he2qpen6xf

creation_rules:
  - path_regex: vars/.*\.yaml$
    key_groups:
      - age:
          - *dev
          - *ci
  - path_regex: vars/.*\.json$
    key_groups:
      - age:
          - *dev
          - *ci
