// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unique identifier for a Todo item.
 *
 * Wraps a UUID v4, providing type safety to prevent mixing up different
 * ID types (e.g., passing a `UserId` where a `TodoId` is expected).
 *
 * # Construction
 *
 * - `TodoId::new()` - Generate a new random ID
 * - `TodoId::from_uuid(uuid)` - Wrap an existing UUID (for deserialization)
 */
export type TodoId = string;
