// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Validated todo text.
 *
 * Guarantees:
 * - Non-empty (at least one non-whitespace character)
 * - At most [`TODO_TEXT_MAX_LENGTH`] characters
 * - Trimmed of leading/trailing whitespace
 *
 * # Example
 *
 * ```rust,ignore
 * let text = TodoText::new("  Buy groceries  ")?;
 * assert_eq!(text.as_str(), "Buy groceries"); // Trimmed
 * ```
 */
export type TodoText = string;
