// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TodoId } from "../domain/TodoId";
import type { TodoText } from "../domain/TodoText";

/**
 * Events emitted by the Todo aggregate.
 *
 * Each variant represents a state change that occurred. The aggregate's
 * current state is the result of applying all its events in order.
 *
 * # Versioning
 *
 * Events have an implicit version (currently v1). Schema evolution is
 * handled by upcasters that transform old event formats during loading.
 * See `EventUpcaster` trait in the infrastructure layer.
 */
export type TodoEvent = { "type": "Created", 
/**
 * Unique identifier for the todo.
 */
id: TodoId, 
/**
 * The todo's text content (validated).
 */
text: TodoText, 
/**
 * When the todo was created.
 */
created_at: string, } | { "type": "TextUpdated", 
/**
 * Which todo was updated.
 */
id: TodoId, 
/**
 * The new text content.
 */
text: TodoText, 
/**
 * When the update occurred.
 */
updated_at: string, } | { "type": "Completed", 
/**
 * Which todo was completed.
 */
id: TodoId, 
/**
 * When it was completed.
 */
completed_at: string, } | { "type": "Uncompleted", 
/**
 * Which todo was uncompleted.
 */
id: TodoId, 
/**
 * When it was uncompleted.
 */
uncompleted_at: string, } | { "type": "Deleted", 
/**
 * Which todo was deleted.
 */
id: TodoId, 
/**
 * When it was deleted.
 */
deleted_at: string, };
